sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: NoTGoYEldExD7PqC4X/wmBHZjDoZs1MGtVGyce4rxPFbk0GzV5LVDVtF/O5qPMHJX/bp88EAoCXH4vsygzD0VZPuSEXdG8s8gf2XZQm0QLgtqfdIpGsecBbn2Mnmo4CFwoUiWiVkFYkpPFJOzGZY7eeKAqiJZ4eYi7mhbvJlm9DHDZ4WyvHQ3wwD25cn9oq5Ef6Zq3xePE0r3QTWKPx8LYPFQJHQcy1N58hDqAPGeohCCn9Vg0uzzMYZF2AAATOOb3TMoUHGovLFnQZ0BnopMcwew3EQH5kOOZeGZGzyJXSx09wns5fX/XJxPatXhY0XpBUF7xEvqFlHjBPgAfGzqmMAdvlJkSG9Yd8+C0zNKjRk73Bw7DD3peUMkepc7hPHvloRqekYCoicS7IZsSzrSD3ay1wcCWGsL+fjmrSkOKxBNmIpz5FPKMcOYBBhV7diYOP7tTLNcudJ8gqeFr+3ipHsIPDoF32JJ5+rdMmYMngXqS8JdbaX5GdS8vt8Zvqp0GzRsLc3682hAeXj5WCei5loPgtMujBfWf/0+GGzNbt2nrgrd8V9JpZkZs/bNCcMMCrUvKXPOTWJVxTN1tnoyfo0BFUAK7N2GnBk9WiCEv9uD1Qy8J7to+oBNkbb4WysN5/KQOuViOkm9v2P+biQC8mhwYzAkbY7SEXqAnTmcoI=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Orlando-Furioso_3747
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy